import React, { ReactNode, useEffect } from 'react';
import { Container, MantineProvider, mergeThemeOverrides } from '@mantine/core';
import { InputFieldRegistryProvider, ThemeKeys, TooltipProvider, containerStyles, resolver, themes } from '@clinicaltoolkits/universal-react-components';
import { DescriptiveRatingTable, VariableGroupSelector, VariableTable, fetchVariableBatch, variableComponentRegistry, variableState, variableTypesWithTwoFields } from '../src/index';
import { useEditor } from "@tiptap/react";
import { contentBlockComponentRegistry, ContentBlockWrapperOptionsProvider, defaultExtensions, RichTextProvider } from '@clinicaltoolkits/content-blocks';
import { RichTextEditor as MantineRichTextEditor } from '@mantine/tiptap';
import { cssVariableOverrides, themeOverridesTest } from './themeOverridesTest';
import { createCTSupabaseClient, getSupabaseClient, setSupabaseClient } from '@clinicaltoolkits/ct-supabase';
import { defineScopes, logger } from '@clinicaltoolkits/logger';


export const TEST_SCOPES = defineScopes("CT/Variables/Test", {
  app_test: true
} as const);

const log = logger.scope(TEST_SCOPES.app_test);
logger.setMinLevel("debug");
logger.enableScope(TEST_SCOPES.app_test);
log.error("scope check", { scope: log.scope });

const componentRegistry = {
  ...variableComponentRegistry,
  ...contentBlockComponentRegistry
}

interface TestContextWrapperProps {
  children?: ReactNode;  // Define children as an optional prop
}
const mergedTheme = mergeThemeOverrides(themes[ThemeKeys.Default], themeOverridesTest);
export const TestContextWrapper: React.FC<TestContextWrapperProps> = ({ children }) => {
  const ctSupabaseClientConfig = {
    anonKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3cWdva29wc2Ntc2doa3BhcHdlIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY5MTEyMjcxMCwiZXhwIjoyMDA2Njk4NzEwfQ.O9oWtzaMPe5rzs_xt9rieWsw4iROMu42XEja1iIdqA4" // This is the servic_role key it should only be used for testing, allows overriding RLS policies
  }
  const supabaseClient = createCTSupabaseClient(ctSupabaseClientConfig);
  setSupabaseClient(supabaseClient);

  log.debug("Supabase client initialized in TestContextWrapper.");

  return (
    <MantineProvider theme={mergedTheme} cssVariablesResolver={resolver(ThemeKeys.Default, cssVariableOverrides)} defaultColorScheme='auto'>
      <InputFieldRegistryProvider registry={componentRegistry} dataTypesWithTwoFields={variableTypesWithTwoFields}>
        <TooltipProvider>
          <RichTextProvider>
            <ContentBlockWrapperOptionsProvider>
            <Test />
            </ContentBlockWrapperOptionsProvider>
          </RichTextProvider>
        </TooltipProvider>
      </InputFieldRegistryProvider>
    </MantineProvider>
  );
};

/*
const Test: React.FC = () => {
  const editor = useEditor({ extensions: defaultExtensions, editable: false });

  const { addVariableSet } = useVariableContext();
  const [bInitialized, setInitialized] = React.useState(false);


  const handleSignIn = async () => {
    const authTokenResponse = await getSupabaseClient().auth.signInWithPassword({ email: "nicholaskhendrickson@gmail.com", password: "Zargoth.2" });
    if (authTokenResponse.error) {
      console.error("Error signing in: ", authTokenResponse.error);
      return null;
    }
    console.log("Signed in successfully");
  };

  const handleInitializeVariables = async () => {
    const variableSets = await fetchVariableSets();
    variableSets.forEach((variableSet) => {
      addVariableSet(variableSet);
    });
  };

  const handleInitializeTest = async () => {
    await handleSignIn();
    await handleInitializeVariables();
    setInitialized(true);
  };
  
  useEffect(() => {
    handleInitializeTest();
  }, [getSupabaseClient()]);

  return bInitialized ? (
    <MantineRichTextEditor editor={editor}>
      <Container className={containerStyles.mainContent}>
        <VariableTable />
        <VariableSetSelector />
        <DescriptiveRatingTable />
      </Container>
    </MantineRichTextEditor>
  ) : <div>...Signing in</div>;
};
*/

const bInitializeVariables = true;
const Test: React.FC = () => {
  const { catalogStore } = variableState;
  const [bInitialized, setInitialized] = React.useState(false);

  const handleSignIn = async () => {
    const authTokenResponse = await getSupabaseClient().auth.signInWithPassword({ email: "nicholaskhendrickson@gmail.com", password: "Zargoth.2" });
    if (authTokenResponse.error) {
      console.error("Error signing in: ", authTokenResponse.error);
      return null;
    }
    log.debug("Signed in successfully");
  };

  const handleInitializeVariables = async () => {
    if (bInitializeVariables) {
      const variables = await fetchVariableBatch({
        bIncludeAutoGeneratedVariables: true,
        entityVersionId: "5ac2937c-39a5-4638-b510-f58a023e9d96"
      });
      log.debug("Fetched variables: ", variables);
      catalogStore.addVariables(variables);
    } else {
      log.debug("Skipping variable initialization in Test component.");
    }
  };

  const handleInitializeTest = async () => {
    if (bInitialized === false) {
      await handleSignIn();
      await handleInitializeVariables();
      setInitialized(true);
    }
  };
  
  useEffect(() => {
    handleInitializeTest();
  }, [getSupabaseClient()]);

  return bInitialized ? (
      <Container className={containerStyles.mainContent}>
        <VariableTable />
        <VariableGroupSelector
          onVariableValueUpdated={(id, value) => catalogStore.setVariableValue(id, value)}
        />
        <DescriptiveRatingTable />
      </Container>
  ) : <div>...Signing in</div>;
};