import { cloneTemplateBlock, RemapPlaceholdersMode } from "@clinicaltoolkits/content-blocks";
import { getChildVariableIds, getParentVariableId, getVariableIdFromString, Variable, VariableData, createVariable } from "..";
import { setInternalMetadata } from "./internalMetadata";
import { generateUUID } from "@clinicaltoolkits/type-definitions";
import { logger } from "@clinicaltoolkits/utility-functions";

interface CloneVariableOptions {
    variableToClone: Variable;
    newVariableId: string;
    entityId: string;
    entityInstanceId: string;
    variableIdMap?: Record<string, string>;
    remapMode?: RemapPlaceholdersMode;
  }
  
  export const cloneVariable = ({
    variableToClone,
    newVariableId,
    entityId,
    entityInstanceId,
    variableIdMap = {},
    remapMode
  }: CloneVariableOptions): Variable => {
    const newIdToken = variableToClone.getIdToken().cloneWithChanges({
      variableId: newVariableId,
      entityId,
      entityVersionId: entityInstanceId,
    });
  
    let clonedVariableData: VariableData = {
      ...variableToClone.toJSON(),
      idToken: newIdToken,
      entityId,
      entityVersionId: entityInstanceId,
      //...newIdToken, // In case you want to flatten it // TODO: Unneccesary to spread and seems to cause TS errors around the publicly accessible get id() method.
      /**
       * For my own curiosity, GPT claims:
       * Why no error for entityId / entityVersionId?
       * On the class, those are optional (?). When you spread newIdToken, TypeScript can’t prove those keys definitely exist, so it won’t emit the “always overwrites” diagnostic.
       * For id, the class exposes a definite accessor (get id()), so the spread’s type definitely includes id. TS therefore warns that your earlier id: would be overwritten by a later spread (even though at runtime that accessor isn’t spread).
       */
      id: newVariableId,
      // Important: set the id to the new one

    };
  
    // Clone content blocks if present
    if (variableToClone.getContent()) {
      const contentToClone = variableToClone.getContent();
      clonedVariableData.content = {
        ...contentToClone,
        description: contentToClone?.description
          ? cloneTemplateBlock({
              block: contentToClone.description,
              variableIdMap,
              entityId,
              entityInstanceId,
              remapMode,
            })
          : undefined,
        interpretation: contentToClone?.interpretation
          ? cloneTemplateBlock({
              block: contentToClone.interpretation,
              variableIdMap,
              entityId,
              entityInstanceId,
              remapMode,
            })
          : undefined,
      };
    }
  
    // Optional: Clone and remap childVariableIds
    const childVariableIds = getChildVariableIds(variableToClone);
    if (childVariableIds.length) {
      clonedVariableData.metadata = {
        ...variableToClone.getMetadata(),
        childVariableIds: childVariableIds.map(
          (oldId) => variableIdMap[oldId] || oldId
        ),
      };
    }

    clonedVariableData = setInternalMetadata(clonedVariableData, {
        _origin: "cloned",
      });
  
    return createVariable(clonedVariableData);
  };
  
interface IBatchCloneVariableOptions extends Omit<CloneVariableOptions, "variableToClone" | "newVariableId" | "variableIdMap"> {
  variablesToClone: Variable[];
}
interface IBatchCloneVariableResult {
  clonedVariables: Variable[];
  variableIdMap: Record<string, string>;
}
export const batchCloneVariable = ({ variablesToClone, entityId, entityInstanceId, remapMode }: IBatchCloneVariableOptions): IBatchCloneVariableResult => {
  const variableIdMap: Record<string, string> = {};

   // 1. Work on a copy so we don’t reorder the caller’s array
  const sortedVariablesToClone = [...variablesToClone].sort((a, b) => {
    const aAuto = a.getMetadata()?.bAutoGenerated ? 1 : 0;
    const bAuto = b.getMetadata()?.bAutoGenerated ? 1 : 0;
    return aAuto - bAuto; // non-auto (0) before auto (1)
  });
  
  // 2. First pass: seed the map with new UUIDs for *every* variable
  for (const variable of sortedVariablesToClone) {
    const oldId = variable.getVariableId();
    variableIdMap[oldId] = generateUUID();
  }

  // 3. Second pass: override the auto generated variables to preserve suffix
  const clonedVariables = sortedVariablesToClone.map(variable => {
    const oldId = variable.getVariableId();
    let newVariableId = variableIdMap[oldId]!;

    if (variable.getMetadata()?.bAutoGenerated) {
      // split at the *first* underscore
      const idx = oldId.indexOf('_');
      if (idx !== -1) {
        const parentOldId = oldId.slice(0, idx);          // Returns the part before the first underscore, this corresponds to the original parent variable's id
        const suffix      = oldId.slice(idx + 1);         // Returns the part after the first underscore
        const parentNewId = variableIdMap[parentOldId];   // Use the original parent variable's id to find the replacement id we populated for it in the first pass
        // If the parent variable was cloned, we can use its new id to create the new id for the auto-generated variable
        if (parentNewId) {
          newVariableId = `${parentNewId}_${suffix}`;
          variableIdMap[oldId] = newVariableId;
        } else {
          // If the parent variable was not cloned we print an error and keep the old id
          logger.error(`batchCloneVariable() - Parent variable ${parentOldId} was not cloned. Keeping old id ${oldId} for auto-generated variable.`, sortedVariablesToClone);
          newVariableId = oldId;
        }
      }
    }

    const clonedVariable = cloneVariable({
      variableToClone: variable,
      newVariableId,
      entityId: entityId,
      entityInstanceId,
      variableIdMap,
      remapMode
    });

    return clonedVariable;
  });

  return {
    clonedVariables,
    variableIdMap,
  };
};
