import { Variable, VariableData, VariableMap } from "..";

export interface GetVariablesArrayProps {
  inVariableMap: VariableMap;
  inVariableIds?: string[];
  bInIncludeAutoGeneratedVariables?: boolean;
}
export const getVariablesArray = ({ inVariableMap, inVariableIds, bInIncludeAutoGeneratedVariables = true}: GetVariablesArrayProps): Variable[] => {
  let variables: Variable[] = [];

  if (inVariableIds) {
    inVariableIds.map((id) => {
      const variable = inVariableMap.get(id);
      if (!variable) {
        throw Error(`VariableContext::getVariablesArray() - Variable with id ${id} not found`);
      }
      bInIncludeAutoGeneratedVariables ? variables.push(variable) : !variable.getMetadata()?.bAutoGenerated && variables.push(variable);
    });
  } else {
    if (bInIncludeAutoGeneratedVariables) {
      variables = Array.from(inVariableMap.values());
    } else {
      variables = Array.from(inVariableMap.values()).filter((variable) => !variable.getMetadata()?.bAutoGenerated);
    }
  }

  return variables;
};

export const getVariableDataArray = ({ inVariableMap, inVariableIds, bInIncludeAutoGeneratedVariables = true}: GetVariablesArrayProps): VariableData[] => {
  let variableDataArray: VariableData[] = [];

  if (inVariableIds) {
    inVariableIds.map((id) => {
      const variable = inVariableMap.get(id);
      if (!variable) {
        throw Error(`VariableContext::getVariableDataArray() - Variable with id ${id} not found`);
      }
      if (bInIncludeAutoGeneratedVariables) {
        variableDataArray.push(variable.toJSON());
      } else if (!variable.getMetadata()?.bAutoGenerated) {
        variableDataArray.push(variable.toJSON());
      }
    });
  } else {
    if (bInIncludeAutoGeneratedVariables) {
      variableDataArray = Array.from(inVariableMap.values()).map((variable) => variable.toJSON());
    } else {
      variableDataArray = Array.from(inVariableMap.values())
        .filter((variable) => !variable.getMetadata()?.bAutoGenerated)
        .map((variable) => variable.toJSON());
    }
  }

  return variableDataArray;
};
