
import { getSupabaseClient } from "@clinicaltoolkits/ct-supabase";
import { EntityId } from "@clinicaltoolkits/type-definitions";
import { convertDBVariableToVariableData, enrichSubvariableProperties, createAutoGeneratedVariables } from "./utility";
import { fetchDescriptiveRatingsArray, DescriptiveRating } from "../descriptive-ratings";
import { Variable, DBVariable, VariableContent, VariableData, createVariable } from "../types";
import { fetchVariableContent } from "../types/functions/utility";

export interface FetchVariableParams {
  variableId: string;
  entityId?: string;
  entityVersionId?: string;
}

export const fetchVariable = async ({ variableId, entityId, entityVersionId }: FetchVariableParams): Promise<Variable | undefined> => {
  const supabaseClient = getSupabaseClient();
  const { data, error } = await supabaseClient
    .from("variables")
    .select(`*`)
    .eq("id", variableId);
  
  if (error) {
    throw new Error(`Supabase error: ${error.message}`);
  }

  const dbVariable: DBVariable | undefined = data?.[0] as any; // TODO: fix types - should not need 'as any'
  if (!dbVariable) {
    return undefined;
  }

  // Convert database rows to application model
  const convertedVariableData = await convertDBVariableToVariableData({ 
    dbVariable,
    entityId,
    entityVersionId,
  });

  return createVariable(convertedVariableData);
};

export interface FetchVariablesParams extends Omit<FetchVariableParams, "variableId"> {
  variableIds?: string[];
  variableSetId?: string;
  descriptiveRatingId?: string;
  bIncludeAutoGeneratedVariables?: boolean;
}
export const fetchVariableBatch = async ({
  variableIds,
  entityId,
  entityVersionId,
  variableSetId,
  descriptiveRatingId,
  bIncludeAutoGeneratedVariables = true,
}: FetchVariablesParams): Promise<Variable[]> => {
    const supabaseClient = getSupabaseClient();
    let query = supabaseClient
      .from("variables")
      .select(`*`)

    if (variableIds) {
      query = query.in("id", variableIds);
    }

    if (entityVersionId) {
      query = query.eq("entity_version_id", entityVersionId);
    }

    try {
      const { data, error } = await query;

      if (error) {
        throw new Error(`Supabase error: ${error.message}`);
      }

      // TODO: This isn't the most elegant solution, but it works for now. Primarily used to auto set the city and province for the demographics section
      let callingUser = undefined;
      if (entityId === EntityId.DEMOGRAPHICS) {
        const userResponse = await supabaseClient.auth.getUser();
        callingUser = userResponse?.data?.user;
      }
      // TODO: Need to revampe the CRUD flow for descriptive ratings. They should follow the format of variable level overrides entity level (if present). Should likely normalize ownership via the database rather than lumping them into json, but we'll see.
      let prefetchedGroupDescriptiveRatings: DescriptiveRating[] | undefined = undefined;
      if (descriptiveRatingId) {
        prefetchedGroupDescriptiveRatings = await fetchDescriptiveRatingsArray(descriptiveRatingId);
      }

      // Batch fetch variable contents
      const variableContentPromises = data.map(dbVariable =>
        fetchVariableContent(
          dbVariable.id,
          undefined,
          entityId,
          entityVersionId
        )
      );
      const variableContents = await Promise.all(variableContentPromises);
      const variableIdToContentMap = new Map<string, VariableContent>();
      data.forEach((dbVariable, index) => {
        const content = variableContents[index];
        if (content) variableIdToContentMap.set(dbVariable.id, content);
      });

      let additionalAccPromises: Promise<void>[] = [];

      const finalData: VariableData[] = await (data as unknown as DBVariable[])?.reduce<Promise<VariableData[]>>( // TODO: fix types - should not need 'as unknown as'
        async (accPromise, dbVariable: DBVariable) => {
          const acc = await accPromise;

          const variableContent = variableIdToContentMap.get(dbVariable.id);

          // Convert database rows to application model
          let convertedVariableData = await convertDBVariableToVariableData({
            dbVariable,
            entityId,
            entityVersionId,
            callingUser,
            prefetchedGroupDescriptiveRatings,
            variableContent,
            additionalAccPromises,
            internalVariableMetadata: {
              _origin: "db",
            },
          });

          // Add the converted variable to the accumulator
          acc.push(convertedVariableData);

          // Create auto-generated variables if necessary
          if (bIncludeAutoGeneratedVariables) {
            createAutoGeneratedVariables(convertedVariableData, acc, additionalAccPromises, prefetchedGroupDescriptiveRatings);
          }

          // Return the accumulator with the new variable and any auto-generated variables
          return acc;
        },
        Promise.resolve([]) // Start with a resolved promise of an empty array in order to allow async operations in conjunction with reduce
      ) ?? [];

      // Wait for all additional promises to complete (i.e., any internal async operations in the loop above)
      await Promise.all(additionalAccPromises);

      // Enrich the associatedSubvariableProperties with actual subvariable names
      for (const variableDatum of finalData) {
        enrichSubvariableProperties(variableDatum, finalData);
      }

      return createVariable(finalData);
    } catch (error) {
      console.error(`Failed to fetch variables ${variableIds}.`, error);
      throw error;
    }
}

export { fetchVariableBatch as fetchVariables };
