
import { DataType, generateUUID } from "@clinicaltoolkits/type-definitions";
import { getAbbreviatedVariablePlaceholder, getVariablePlaceholder } from "./getPlaceholders";
import { Variable, VariableData } from "../../types";

// Function to initialize metadata and childVariableKeys if they are not present
export function initializeVariableDataMetadata(variableData: VariableData) {
  if (variableData.metadata === null || variableData.metadata === undefined) {
    variableData.metadata = {};
  }

  if (!variableData.metadata.childVariableIds) {
    variableData.metadata.childVariableIds = [];
  }
}

// Function to create a base variable template
function createBaseVariableDataTemplate(variableData: VariableData): VariableData {
  return {
    ...variableData,
    content: undefined,
    metadata: { label: variableData.metadata?.label },
  };
}

// Function to create the percentile rank variable
export function createPercentileRankVariableData(parentVariableData: VariableData, bAutoGenerated?: boolean): VariableData {
  const childVariableIdToken = parentVariableData.idToken.cloneWithChanges({ variableId: `${parentVariableData.idToken.variableId}_${DataType.PERCENTILE_RANK}` });

  // Initialize metadata and childVariableKeys
  initializeVariableDataMetadata(parentVariableData);
  const childVariableTemplate = createBaseVariableDataTemplate(parentVariableData);
  parentVariableData.metadata?.childVariableIds?.push(childVariableIdToken.id);

  return {
    ...childVariableTemplate,
    idToken: childVariableIdToken,
    fullName: `${parentVariableData.fullName} Percentile Rank`,
    abbreviatedName: `${parentVariableData.abbreviatedName}_percentile_rank`,
    dataType: DataType.PERCENTILE_RANK,
    metadata: {
      label: `${parentVariableData.metadata?.label}`,
      visibility: parentVariableData.metadata?.percentileRankVisibility,
      bOptional: parentVariableData.metadata?.bOptional,
      bNormallyDistributed: parentVariableData.metadata?.bNormallyDistributed,
      properties: {
        childVariable: {
          parentVariableId: parentVariableData.idToken.id,
        },
        sectionSubversion: parentVariableData.metadata?.properties?.sectionSubversion,
      },
      placeholder: getVariablePlaceholder(DataType.PERCENTILE_RANK),
      abbreviatedPlaceholder: getAbbreviatedVariablePlaceholder(DataType.PERCENTILE_RANK),
      bChild: true,
      bAutoGenerated: bAutoGenerated,
    },
  };
}

export function createPercentileRangeVariableData(parentVariableData: VariableData, bAutoGenerated?: boolean): VariableData {
  const childVariableIdToken = parentVariableData.idToken.cloneWithChanges({ variableId: `${parentVariableData.idToken.variableId}_${DataType.PERCENTILE_RANGE}` });

  // Initialize metadata and childVariableKeys
  initializeVariableDataMetadata(parentVariableData);
  const childVariableTemplate = createBaseVariableDataTemplate(parentVariableData);
  parentVariableData.metadata?.childVariableIds?.push(childVariableIdToken.id);

  return {
    ...childVariableTemplate,
    idToken: childVariableIdToken,
    fullName: `${parentVariableData.fullName} Percentile Range`,
    abbreviatedName: `${parentVariableData.abbreviatedName}_percentile_range`,
    dataType: DataType.PERCENTILE_RANGE,
    metadata: {
      label: `${parentVariableData.metadata?.label}`,
      visibility: parentVariableData.metadata?.percentileRangeVisibility,
      bOptional: parentVariableData.metadata?.bOptional,
      properties: {
        childVariable: {
          parentVariableId: parentVariableData.idToken.id,
        },
        sectionSubversion: parentVariableData.metadata?.properties?.sectionSubversion,
      },
      placeholder: getVariablePlaceholder(DataType.PERCENTILE_RANGE),
      abbreviatedPlaceholder: getAbbreviatedVariablePlaceholder(DataType.PERCENTILE_RANGE),
      bChild: true,
      bAutoGenerated: bAutoGenerated,
    },
  };
}

// Function to create the descriptor variable
export function createDescriptorVariableData(parentVariableData: VariableData, bAutoGenerated?: boolean): VariableData {
  const childVariableIdToken = parentVariableData.idToken.cloneWithChanges({ variableId: `${parentVariableData.idToken.variableId}_${DataType.DESCRIPTOR}` });

  // Initialize metadata and childVariableKeys
  initializeVariableDataMetadata(parentVariableData);
  const childVariableTemplate = createBaseVariableDataTemplate(parentVariableData);
  parentVariableData.metadata?.childVariableIds?.push(childVariableIdToken.id);

  return {
    ...childVariableTemplate,
    idToken: childVariableIdToken,
    fullName: `${parentVariableData.fullName} Descriptor`,
    abbreviatedName: `${parentVariableData.abbreviatedName}_descriptor`,
    dataType: DataType.DESCRIPTOR,
    metadata: {
      label: `${parentVariableData.metadata?.label}`,
      visibility: parentVariableData.metadata?.descriptiveRatingVisibility,
      bOptional: parentVariableData.metadata?.bOptional,
      properties: {
        childVariable: {
          parentVariableId: parentVariableData.idToken.id,
        },
        sectionSubversion: parentVariableData.metadata?.properties?.sectionSubversion,
      },
      descriptiveRatings: [],
      placeholder: getVariablePlaceholder(DataType.DESCRIPTOR),
      abbreviatedPlaceholder: getAbbreviatedVariablePlaceholder(DataType.DESCRIPTOR),
      bChild: true,
      bAutoGenerated: bAutoGenerated,
    },
  };
}

export function createPreviousScoreVariableData(parentVariableData: VariableData, bAutoGenerated?: boolean): VariableData {
  const childVariableIdToken = parentVariableData.idToken.cloneWithChanges({ variableId: `${parentVariableData.idToken.variableId}_previous_score` });

  // Initialize metadata and childVariableKeys
  initializeVariableDataMetadata(parentVariableData);
  const childVariableTemplate = createBaseVariableDataTemplate(parentVariableData);
  parentVariableData.metadata?.childVariableIds?.push(childVariableIdToken.id);

  return {
    ...childVariableTemplate,
    idToken: childVariableIdToken,
    fullName: `${parentVariableData.fullName} Previous Score`,
    abbreviatedName: `${parentVariableData.abbreviatedName}_previous_score`,
    dataType: parentVariableData.dataType,
    metadata: {
      label: `${parentVariableData.metadata?.label}`,
      visibility: parentVariableData.metadata?.previousScoreVisibility,
      bOptional: parentVariableData.metadata?.bOptional,
      properties: {
        childVariable: {
          parentVariableId: parentVariableData.idToken.id,
        },
        sectionSubversion: parentVariableData.metadata?.properties?.sectionSubversion,
      },
      placeholder: "Previous Score",
      abbreviatedPlaceholder: "Previous Score",
      bChild: true,
      bAutoGenerated: bAutoGenerated,
    },
  };
}
