
import { DataType } from "@clinicaltoolkits/type-definitions";
import { Variable, VariableData, wrapVariables } from "../../types";
import { getUniversalDescriptiveRatings } from "../../descriptive-ratings/utility/getUniversalRatings";
import { createDescriptorVariableData, createPercentileRangeVariableData, createPercentileRankVariableData, createPreviousScoreVariableData } from "./ChildVariables";
import { fetchDescriptiveRatingsArray, DescriptiveRating, getOptionsFromDescriptiveRatings } from "../../descriptive-ratings";

export const createAutoGeneratedVariables = (variableData: VariableData, accumulator?: VariableData[], accumulatorPromises?: Promise<void>[], globallyAppliedDescriptiveRatings?: DescriptiveRating[]): void => {
  if (variableData.metadata?.bCreatePercentileRank) {
    const percentileRankVariableData = createPercentileRankVariableData(variableData, true);
    accumulator?.push(percentileRankVariableData);
  }

  if (variableData.metadata?.bCreateDescriptiveRating) {
    const descriptorVariableData = createDescriptorVariableData(variableData, true);
    applyDescriptiveRatings(descriptorVariableData, variableData.dataType, variableData?.metadata?.descriptiveRatingId, globallyAppliedDescriptiveRatings, accumulatorPromises);
    accumulator?.push(descriptorVariableData);
  }

  if (variableData.metadata?.bCreatePreviousScore) {
    const previousScoreVariableData = createPreviousScoreVariableData(variableData, true);
    accumulator?.push(previousScoreVariableData);
  }

  if (variableData.metadata?.bCreatePercentileRange) {
    const percentileRangeVariableData = createPercentileRangeVariableData(variableData, true);
    accumulator?.push(percentileRangeVariableData);
  }
};

export async function applyDescriptiveRatings(variableData: VariableData, dataType: DataType, descriptiveRatingId?: string, globallyAppliedDescriptiveRatings?: DescriptiveRating[], additionalAccPromises?: Promise<void>[]): Promise<void> {
  if (!variableData.metadata) {
    variableData.metadata = {
      descriptiveRatings: [],
    };
  }
  if (descriptiveRatingId) {
    const fetchPromise = fetchDescriptiveRatingsArray(descriptiveRatingId).then((ratings) => {
      variableData.metadata!.descriptiveRatings = ratings;
      variableData.metadata!.dropdownOptions = getOptionsFromDescriptiveRatings(ratings, dataType);
    });
    if (additionalAccPromises) {
      additionalAccPromises?.push(fetchPromise);
    } else {
      await fetchPromise;
    }
  } else if (globallyAppliedDescriptiveRatings) {
    variableData.metadata!.descriptiveRatings = globallyAppliedDescriptiveRatings;
    variableData.metadata!.dropdownOptions = getOptionsFromDescriptiveRatings(globallyAppliedDescriptiveRatings, dataType);
  } else {
    const universalDescriptiveRatings = getUniversalDescriptiveRatings();
    variableData.metadata!.descriptiveRatings = universalDescriptiveRatings;
    variableData.metadata!.dropdownOptions = getOptionsFromDescriptiveRatings(universalDescriptiveRatings, dataType);
  }
}