import { ComboboxData } from "@clinicaltoolkits/type-definitions";
import { fetchVariables } from "../fetchVariable";
import { convertVariablesToComboboxData } from "../../types";

export const fetchVariablesComboboxData = async (): Promise<ComboboxData[]> => {
  const variables = await fetchVariables({ bIncludeAutoGeneratedVariables: false });
  const variableComboboxData = convertVariablesToComboboxData(variables);
  return variableComboboxData;
};
