import { defineScopes } from "@clinicaltoolkits/logger";
import { createAutoGeneratedVariables } from "./database";

export const SCOPES = defineScopes("CT/Variables", {
  types: {
    functions: {
      utility: {
          get_variable_content: true,
          get_percentile_rank: true,
      },
      automated_updates: {
          derive_auto_variable_updates: true,
          assessment_age: true,
      },
      assosciated_variables: {
          update_associated_subvariables: true,
      }
    }
  },
  database: {
    utility: {
        database_conversions: true,
        createAutoGeneratedVariables: true,
        enrichSubvariableProperties: true
    }
  },
  components: {
    variable_group_modal: {
      variable_group_modal: true
    }
  },
  descriptive_ratings: {
    utility: {
      get_universal_ratings: true,
      get_descriptive_ratings: true,
    }
  }
} as const);
