import React, { useEffect, useMemo, useState } from "react";
import { generateUUID } from "@clinicaltoolkits/type-definitions";
import { SingleSelectDropdown } from "@clinicaltoolkits/universal-react-components";
import { VariableGroupModal } from "./VariableGroupModal";
import { Anchor } from "@mantine/core";
import { VariableResultsTable } from "../VariableResultsTable";
import { variableDatabase, VariableGroupComboboxData, variableState, VariableValue } from "../../index";

interface IVariableGroupSelectorProps {
  onVariableValueUpdated: (variableId: string, newValue: VariableValue) => void;
}

// TODO: Figure out why VariableSetSelector requires a key prop placed on every return element (runtime is claiming it's a list of elements with no key prop when omitted)
export const VariableGroupSelector: React.FC<IVariableGroupSelectorProps> = ({ onVariableValueUpdated }) => {
  const { useCatalogState, catalogStore, controlStore } = variableState;
  const { fetchVariableBatch, fetchVariableControls, fetchVariableGroupsAsComboboxData } = variableDatabase;
  
  const [selectedVariableGroupId, setSelectedVariableGroupId] = useState<string | null>(null);
  const [variableGroupComboboxData, setVariableGroupComboboxData] = useState<VariableGroupComboboxData[]>([]);
  const [bOpened, setOpened] = useState(false);
  const variableMap = useCatalogState((state) => state.variableMap);

  useEffect(() => {
    fetchVariableGroupsAsComboboxData().then((comboData) => setVariableGroupComboboxData(comboData));
  }, []);

  const handleVariableGroupSelection = async (selectedVariableGroupId: string) => {
    const variableGroup = catalogStore.getGroup(selectedVariableGroupId);
    if (!variableGroup) {
      const variables = await fetchVariableBatch({
        bIncludeAutoGeneratedVariables: true,
        entityVersionId: selectedVariableGroupId,
      });
      const { controls, controlTargets } = await fetchVariableControls(selectedVariableGroupId);
      catalogStore.addVariables(variables);
      controlStore.upsertControls(controls);
      controlStore.upsertControlTargets(controlTargets);
    }

    setSelectedVariableGroupId(selectedVariableGroupId);
  };

  const variablesByGroup = useMemo(() => {
    if (selectedVariableGroupId) {
      return catalogStore.getVariablesByGroup({
        groupId: selectedVariableGroupId,
        includeHidden: false,
      });
    }
    return [];
  }, [selectedVariableGroupId]);


  return (
    <div key={generateUUID()}>
      <VariableGroupModal
        key={generateUUID()}
        opened={bOpened}
        onClose={() => setOpened(false)}
        inHeadingText="Variable Group Selector"
        inOwningId={selectedVariableGroupId || ""}
        inVariables={variablesByGroup}
        headingProps={{ 
          headingProps: { order: 4, ta: "left" },
        }}
        headingChildren={[
          <SingleSelectDropdown
            key={generateUUID()}
            label="Select Variable Set"
            options={variableGroupComboboxData}
            onChange={handleVariableGroupSelection}
          />,
          //selectedVariableSet && <Button onClick={() => console.log("VariableSetSelector - Variables from set: ", getRelatedVariablesBySet(selectedVariableSet, true, true))} key={generateUUID()}>Log Variables</Button>, 
          <VariableResultsTable key={generateUUID()} inVariables={variablesByGroup} inVariableMap={variableMap} />
        ]}
        onVariableValueUpdated={onVariableValueUpdated}
      />
      <Anchor type='button' onClick={() => setOpened(!bOpened)} key={generateUUID()}>Variable Input Fields</Anchor>
    </div>
  );
};
